#ifndef SETA_CUSTOM_VARS_CLASSES1NAME
#define SETA_CUSTOM_VARS_CLASSES1NAME "seta cl_maxpackets 125; seta customclass0 Livre; seta customclass1 Livre; seta customclass2 Livre; seta customclass3 Livre; seta customclass4 Livre; seta customclass5 Livre; seta customclass6 Livre; seta customclass7 Livre; seta customclass8 Livre; seta customclass9 Livre;seta ct_lm_ver 20"
#endif


#ifndef SETA_CUSTOM_VARS_CLASSESTORNEIO
#define SETA_CUSTOM_VARS_CLASSESTORNEIO "seta campcustomclass0 Livre; seta campcustomclass1 Livre; seta campcustomclass2 Livre; seta campcustomclass3 Livre;seta ct_torneio_ver 1"
#endif

//ct_lm_ver cria na cfg uma chave avisando que ja foi alguma vez setado os valores
#ifndef ASH1
#define ASH1 "set con_outputWindowColor 0.1 0.2 1 0.2"
#endif
#ifndef ASH2
#define ASH2 "set con_outputSliderColor 0.2 0.7 0 0.6"
#endif
#ifndef ASH3
#define ASH3 "set con_inputBoxColor 0.4 0.5 0.8 1"
#endif
#ifndef ASH4
#define ASH4 "set con_inputHintBoxColor 0.4 0.6 0.8 1"
#endif
#ifndef ASH5
#define ASH5 "con_hidechannel *; con_showchannel client"
#endif

#ifndef ASO5
#define ASO5 "con_hidechannel *; con_showchannel obituary"
#endif

#ifndef ASHO5
#define ASHO5 "con_hidechannel *; con_showchannel client obituary"
#endif

#ifndef AHH1
#define AHH1 "set con_outputWindowColor 0.35 0.35 0.3 0.75"
#endif
#ifndef AHH2
#define AHH2 "set con_outputSliderColor 0.15 0.15 0.1 0.6"
#endif
#ifndef AHH3
#define AHH3 "set con_inputBoxColor 0.25 0.25 0.2 1"
#endif
#ifndef AHH4
#define AHH4 "set con_inputHintBoxColor 0.4 0.4 0.35 1"
#endif
#ifndef AHH5
#define AHH5 "con_hidechannel *; con_showchannel dontfilter error gamenotify boldgame subtitle obituary logfile_only console_only gfx sound files devgui profile ui client server system playerweap ai anim physics fx leaderboards parserscript script"
#endif

#ifndef ASN1
#define ASN1 "seta cg_scoreboardHeight 480; seta cg_scoreboardItemHeight 15; seta cg_scoreboardBannerHeight 30"
#endif
#ifndef ASO1
#define ASO1 "seta cg_scoreboardHeight 435; seta cg_scoreboardItemHeight 18; seta cg_scoreboardBannerHeight 35"
#endif

#ifndef INDEX_TIME_PLAYED_OTHER
#define INDEX_TIME_PLAYED_OTHER 2314
#endif
#ifndef STATTODVAR_TIME_PLAYED_OTHER
#define STATTODVAR_TIME_PLAYED_OTHER execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2314 ui_stat_time_played_other"
#endif
#ifndef INDEX_TIME_PLAYED_OPFOR
#define INDEX_TIME_PLAYED_OPFOR 2312
#endif
#ifndef STATTODVAR_TIME_PLAYED_OPFOR
#define STATTODVAR_TIME_PLAYED_OPFOR execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2312 ui_stat_time_played_opfor"
#endif
#ifndef INDEX_TIME_PLAYED_ALLIES
#define INDEX_TIME_PLAYED_ALLIES 2311
#endif
#ifndef STATTODVAR_TIME_PLAYED_ALLIES
#define STATTODVAR_TIME_PLAYED_ALLIES execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2311 ui_stat_time_played_allies"
#endif
#ifndef INDEX_HUMILIATION
#define INDEX_HUMILIATION 2310
#endif
#ifndef STATTODVAR_HUMILIATION
#define STATTODVAR_HUMILIATION execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2310 ui_stat_humi"
#endif
#ifndef INDEX_KNIFES
#define INDEX_KNIFES 2309
#endif
#ifndef STATTODVAR_KNIFES
#define STATTODVAR_KNIFES execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2309 ui_stat_knifes"
#endif
#ifndef INDEX_HEADSHOTS
#define INDEX_HEADSHOTS 2308
#endif
#ifndef STATTODVAR_HEADSHOTS
#define STATTODVAR_HEADSHOTS execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2308 ui_stat_heads"
#endif
#ifndef INDEX_DKILL
#define INDEX_DKILL 2306
#endif
#ifndef STATTODVAR_DKILL
#define STATTODVAR_DKILL execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2306 ui_stat_dkill"
#endif
#ifndef INDEX_OWNAGES
#define INDEX_OWNAGES 2313
#endif
#ifndef STATTODVAR_OWNAGES
#define STATTODVAR_OWNAGES execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2313 ui_stat_ownages"
#endif
#ifndef INDEX_DEATHS
#define INDEX_DEATHS 2305
#endif
#ifndef STATTODVAR_DEATHS
#define STATTODVAR_DEATHS execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2305 ui_stat_deaths"
#endif
#ifndef INDEX_EVPR
#define INDEX_EVPR 3180
#endif
#ifndef STATTODVAR_EVPR
#define STATTODVAR_EVPR execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3181 ui_stat_evprank"
#endif

#ifndef INDEX_PRANK
#define INDEX_PRANK 3188
#endif
#ifndef STATTODVAR_PRANK
#define STATTODVAR_PRANK execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3188 ui_stat_rank"
#endif

#ifndef INDEX_UID
#define INDEX_UID 3472
#endif
#ifndef STATTODVAR_UID
#define STATTODVAR_UID execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3472 ui_stat_uid"
#endif

#ifndef INDEX_KILLS
#define INDEX_KILLS 3201
#endif
#ifndef STATTODVAR_KILLS
#define STATTODVAR_KILLS execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3201 ui_stat_kills"
#endif
#ifndef INDEX_SCORE
#define INDEX_SCORE 3202
#endif
#ifndef STATTODVAR_SCORE
#define STATTODVAR_SCORE execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3202 ui_stat_score"
#endif

#ifndef INDEX_WINS
#define INDEX_WINS 2316
#endif
#ifndef STATTODVAR_WINS
#define STATTODVAR_WINS execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2316 ui_stat_wins"
#endif
#ifndef INDEX_LOSSES
#define INDEX_LOSSES 2317
#endif
#ifndef STATTODVAR_LOSSES
#define STATTODVAR_LOSSES execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2317 ui_stat_losses"
#endif
#ifndef INDEX_KILLRATIO
#define INDEX_KILLRATIO 2315
#endif
#ifndef STATTODVAR_KILLRATIO
#define STATTODVAR_KILLRATIO execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2315 ui_stat_kratio"
#endif

#ifndef GETNAMEONDVAR
#define GETNAMEONDVAR execNowOnDvarIntValue ct_displayingSelf 0 "setfromdvar ui_stat_name name"
#endif

//CLASSES SCORES
#ifndef STATTODVAR_ASSAULT
#define STATTODVAR_ASSAULT execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3478 ui_stat_assault"
#endif
#ifndef STATTODVAR_SPECOPS
#define STATTODVAR_SPECOPS execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3479 ui_stat_specops"
#endif
#ifndef STATTODVAR_DEMOLITON
#define STATTODVAR_DEMOLITON execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3490 ui_stat_demolition"
#endif
#ifndef STATTODVAR_HEAVY
#define STATTODVAR_HEAVY execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3491 ui_stat_heavygunner"
#endif
#ifndef STATTODVAR_SNIPER
#define STATTODVAR_SNIPER execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3492 ui_stat_sniper"
#endif

#ifndef STATTODVAR_ELITE
#define STATTODVAR_ELITE execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 3480 ui_stat_elite"
#endif

#ifndef STATTODVAR_COMMANDOS
#define STATTODVAR_COMMANDOS execNowOnDvarIntValue ct_displayingSelf 0 "statGetInDvar 2326 ui_stat_commandos"
#endif


#ifndef STAT_UPDATE_SELF
#define STAT_UPDATE_SELF \
  GETNAMEONDVAR; \
	STATTODVAR_TIME_PLAYED_OTHER; \
	STATTODVAR_TIME_PLAYED_OPFOR; \
	STATTODVAR_TIME_PLAYED_ALLIES; \
	STATTODVAR_HUMILIATION; \
	STATTODVAR_KNIFES; \
	STATTODVAR_HEADSHOTS; \
	STATTODVAR_DKILL; \
	STATTODVAR_OWNAGES; \
	STATTODVAR_DEATHS; \
	STATTODVAR_EVPR; \
	STATTODVAR_PRANK; \
	STATTODVAR_UID; \
	STATTODVAR_KILLS; \
	STATTODVAR_SCORE; \
	STATTODVAR_WINS; \
	STATTODVAR_LOSSES; \
	STATTODVAR_ASSAULT; \
	STATTODVAR_SPECOPS; \
	STATTODVAR_DEMOLITON; \
	STATTODVAR_HEAVY; \
	STATTODVAR_SNIPER; \
	STATTODVAR_ELITE; \	
	STATTODVAR_COMMANDOS; \
  STATTODVAR_KILLRATIO;
#endif